### PR TITLE
Fix for the experimental SSL support

### PR DESCRIPTION
**Pull request by theju**
Using `cond` instead of `case` because `case` uses `eql` for comparison.

### CODE REVIEW

**Comment by nicferrier** [comment]
Btw you are putting tabs in your files. Very bad.

**Comment by theju** [comment]
Oops, sorry about the whitespace mixing.

**Comment by theju** [comment]
`tab-width` 4 is good? I happened to be using the default which happens to be 8.

**Comment by nicferrier** [comment]
It's not the tab width, it's the putting tabs in files I object to. Because no one can agree on what tab-width is it's better to use spaces. You ought to be able to infer the indentation details for elisp (I use pretty standard rules) from the file.

**Pull request merged**
